# Generated by Django 4.2.2 on 2023-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=30)),
                ('productprice', models.IntegerField()),
                ('productMFD', models.DateField()),
                ('productEPD', models.DateField()),
            ],
        ),
    ]
