# Generated by Django 4.2.2 on 2023-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=50)),
                ('Marks', models.IntegerField()),
            ],
        ),
    ]
